# .goreleaser.yml

project_name: srtran

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/s0up4200/SRTran/cmd.version={{.Version}} -X github.com/s0up4200/SRTran/cmd.buildDate={{.Date}} -X github.com/s0up4200/SRTran/cmd.commit={{.Commit}}
    main: .
    binary: srtran

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

# Homebrew formula
brews:
  - homepage: https://github.com/s0up4200/SRTran
    description: A tool to translate .srt subtitles from one language to another
    license: GPL-2.0-or-later
    repository:
      owner: s0up4200
      name: homebrew-srtran
    directory: Formula
    test: |
      system "#{bin}/srtran version" 